// <auto-generated />
using System;
using DiplomaTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922214926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaTracker.Api.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClaimReopened")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ArchivedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(302)
                        .HasColumnType("nvarchar(302)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedGroupId", "StorageKey")
                        .IsUnique();

                    b.HasIndex("ArchivedGroupId", "StudentName", "StepOrder", "Version");

                    b.ToTable("ArchivedFiles", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("GroupDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceGroupId")
                        .IsUnique();

                    b.HasIndex("AcademicYear", "GroupCode");

                    b.ToTable("ArchivedGroups", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedGroupReviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArchivedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(302)
                        .HasColumnType("nvarchar(302)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ArchivedGroupId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("ArchivedGroupReviewers", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId", "Name")
                        .IsUnique();

                    b.HasIndex("FacultyId", "ShortName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DiplomaTaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("Title");

                    b.HasIndex("FacultyId", "Order")
                        .IsUnique();

                    b.ToTable("DiplomaTaskTemplates", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VisibleToAllStudents")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleToAllTeachers")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DocumentTemplates", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplateGroup", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("DocumentTemplateGroups", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplateTeacher", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemplateId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("DocumentTemplateTeachers", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Faculties", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("AcademicYear", "Code")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.GroupReviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("GroupId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("GroupReviewers", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.GroupTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiplomaTaskTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaTaskTemplateId");

                    b.HasIndex("GroupId", "DiplomaTaskTemplateId")
                        .IsUnique();

                    b.ToTable("GroupTasks", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.PlatformSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("RegistrationOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TopicSelectionDeadline")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlatformSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegistrationOpen = false
                        });
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StudentNumberCanonical")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentNumberCanonical")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TopicId")
                        .IsUnique()
                        .HasFilter("[TopicId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Mark")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupTaskId");

                    b.HasIndex("StudentProfileId", "GroupTaskId")
                        .IsUnique();

                    b.ToTable("StudentTasks", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<int?>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("Decision", "SubmittedAt");

                    b.HasIndex("StudentTaskId", "Version")
                        .IsUnique();

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.SubmissionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionFiles", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("DepartmentId", "Status");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.TopicReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId")
                        .IsUnique()
                        .HasDatabaseName("IX_TopicReservations_ActivePerTopic")
                        .HasFilter("[TopicId] IS NOT NULL AND [Status] IN ('Pending', 'Approved')");

                    b.HasIndex("StudentProfileId", "CreatedAt");

                    b.HasIndex(new[] { "StudentProfileId" }, "IX_TopicReservations_ApprovedPerStudent")
                        .IsUnique()
                        .HasFilter("[Status] = 'Approved'");

                    b.HasIndex(new[] { "StudentProfileId" }, "IX_TopicReservations_PendingPerStudent")
                        .IsUnique()
                        .HasFilter("[Status] = 'Pending'");

                    b.ToTable("TopicReservations", (string)null);
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedFile", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.ArchivedGroup", "ArchivedGroup")
                        .WithMany("Files")
                        .HasForeignKey("ArchivedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedGroup");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedGroupReviewer", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.ArchivedGroup", "ArchivedGroup")
                        .WithMany("Reviewers")
                        .HasForeignKey("ArchivedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedGroup");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Department", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DiplomaTaskTemplate", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Faculty", "Faculty")
                        .WithMany("TaskTemplates")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplate", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplateGroup", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.DocumentTemplate", "Template")
                        .WithMany("Groups")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplateTeacher", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.DocumentTemplate", "Template")
                        .WithMany("Teachers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Group", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Department", "Department")
                        .WithMany("Groups")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.GroupReviewer", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Group", "Group")
                        .WithMany("Reviewers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Reviewer")
                        .WithMany("GroupReviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.GroupTask", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.DiplomaTaskTemplate", "DiplomaTaskTemplate")
                        .WithMany("GroupTasks")
                        .HasForeignKey("DiplomaTaskTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.Group", "Group")
                        .WithMany("GroupTasks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiplomaTaskTemplate");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentProfile", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Supervisor")
                        .WithMany("SupervisedStudents")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiplomaTracker.Api.Entities.Topic", "Topic")
                        .WithMany("Holders")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("DiplomaTracker.Api.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Supervisor");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentTask", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.GroupTask", "GroupTask")
                        .WithMany("StudentTasks")
                        .HasForeignKey("GroupTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("StudentTasks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupTask");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Submission", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Reviewer")
                        .WithMany("ReviewedSubmissions")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiplomaTracker.Api.Entities.StudentTask", "StudentTask")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("StudentTask");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.SubmissionFile", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Topic", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.Department", "Department")
                        .WithMany("Topics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.AppUser", "Supervisor")
                        .WithMany("SupervisedTopics")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.TopicReservation", b =>
                {
                    b.HasOne("DiplomaTracker.Api.Entities.StudentProfile", "StudentProfile")
                        .WithMany("TopicReservations")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaTracker.Api.Entities.Topic", "Topic")
                        .WithMany("Reservations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudentProfile");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.AppUser", b =>
                {
                    b.Navigation("GroupReviews");

                    b.Navigation("ReviewedSubmissions");

                    b.Navigation("StudentProfile");

                    b.Navigation("SupervisedStudents");

                    b.Navigation("SupervisedTopics");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.ArchivedGroup", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Reviewers");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Department", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DiplomaTaskTemplate", b =>
                {
                    b.Navigation("GroupTasks");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.DocumentTemplate", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("TaskTemplates");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Group", b =>
                {
                    b.Navigation("GroupTasks");

                    b.Navigation("Reviewers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.GroupTask", b =>
                {
                    b.Navigation("StudentTasks");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentProfile", b =>
                {
                    b.Navigation("StudentTasks");

                    b.Navigation("TopicReservations");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.StudentTask", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Submission", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("DiplomaTracker.Api.Entities.Topic", b =>
                {
                    b.Navigation("Holders");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
